TASK86618 : Add support to copy fw_vib json file in release build scripts
hg-changeset: 290cffbcc2167b831c66c8d98a56fee226c9b5a3

diff --git a/scripts/build_sfvmk_pkg b/scripts/build_sfvmk_pkg
--- a/scripts/build_sfvmk_pkg
+++ b/scripts/build_sfvmk_pkg
@@ -249,6 +249,12 @@ if [ $fw_status == "yes" ] ;then
          echo "Aborting!.."
          exit
       fi
+      scp root@$fw_vm:"/root/firmware_vib/firmware/FirmwareMetadata.json" $fw_pkg_dir
+      if [ $? -ne 0 ] ;then
+         echo "ERROR: SCP failed"
+         echo "Aborting!.."
+         exit
+      fi
   fi
   cmd="rm -rf /root/firmware_vib"
   ssh -l root ${fw_vm} "${cmd}"
